### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by sola91** [gutschilla/plug-session-memcached#1]
I am trying to integrate memcached in my project. However, I get the following error:

Looking up alternatives for conflicting requirements on plug
  From mix.lock: 1.0.3
  From plug_session_memcached v0.2.6: ~> 0.13.0

*\* (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

Here is my mix.exs:

defp deps do
    [{:comeonin, "~>1.6"},
     {:phoenix, "~> 1.0.0"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:httpoison, "~> 0.7.2"},
     {:guardian, "~> 0.8.0"},
     {:ua_inspector, "~> 0.10" },
     {:yamerl,       github: "yakaz/yamerl" },
     {:plug_session_memcached, "~> 0.2.0" }
]
  end

Here is my mix.lock:

%{"base64url": {:hex, :base64url, "0.0.1"},
  "comeonin": {:hex, :comeonin, "1.6.0"},
  "connection": {:hex, :connection, "1.0.2"},
  "corman": {:git, "git://github.com/EchoTeam/corman.git", "e3c4c9f602441b4d9b8f9f8ea2813b3d791ec9e1", [branch: "master"]},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "decimal": {:hex, :decimal, "1.1.1"},
  "dht_ring": {:git, "git://github.com/EchoTeam/dht_ring.git", "d5b880ad76aefc81547dbb76b48a97a01d52ff41", [branch: "master"]},
  "ecto": {:hex, :ecto, "1.1.1"},
  "fs": {:hex, :fs, "0.9.2"},
  "goldrush": {:git, "git://github.com/DeadZen/goldrush.git", "1d883423ac360b3536ca52dc733a0164bacf3109", [tag: "0.1.5"]},
  "guardian": {:hex, :guardian, "0.8.1"},
  "hackney": {:hex, :hackney, "1.3.2"},
  "httpoison": {:hex, :httpoison, "0.7.5"},
  "idna": {:hex, :idna, "1.0.2"},
  "joken": {:hex, :joken, "0.15.0"},
  "jose": {:hex, :jose, "1.4.2"},
  "lager": {:git, "git://github.com/basho/lager.git", "ad400896af5b1ad8b4f7a4d34e609b5a990640bb", [tag: "2.0.1"]},
  "phoenix": {:hex, :phoenix, "1.0.4"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "1.2.0"},
  "phoenix_html": {:hex, :phoenix_html, "2.3.0"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.1"},
  "plug": {:hex, :plug, "1.0.3"},
  "poison": {:hex, :poison, "1.5.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.10.0"},
  "ranch": {:hex, :ranch, "1.2.0"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.6"},
  "ua_inspector": {:hex, :ua_inspector, "0.10.0"},
  "uuid": {:hex, :uuid, "1.1.2"},
  "yamerl": {:git, "git://github.com/yakaz/yamerl.git", "ae810a808817d9482b4628ae3e20d746e3729fe0", []}}

**Comment by gutschilla** [comment]
Oops, didn't update this for a while, stay tuned for the already existing fix to be pushed soon. Haven't taken my laptop with me for new year's vacations ;-) 

Thanks for pointing me to this.

**Comment by gutschilla** [comment]
Fixed. Again, thanks.
