### ISSUE TITLE
Error at compilation time

### ISSUE THREAD

**Issue by sola91** [gutschilla/plug-session-memcached#2]
I configured the plug as in the instructions. However, when I start my Phoenix server ("mix phoenix.server"), I receive the following error:

== Compilation error on file lib/video_backend/endpoint.ex ==
*\* (UndefinedFunctionError) undefined function: Plug.Session.MEMCACHED.init/1 (module Plug.Session.MEMCACHED is not available)
    Plug.Session.MEMCACHED.init([table: :memcached_sessions, signing_salt: "123456", encryption_salt: "654321"])
    (plug) lib/plug/session.ex:48: Plug.Session.init/1
    (plug) lib/plug/builder.ex:198: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:186: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:186: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Endpoint.**before_compile**/1
    lib/video_backend/endpoint.ex:1: VideoBackend.Endpoint (module)
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

**Comment by gutschilla** [comment]
Hi @sola91 thanks for pointing me to this! Apparently, mix/hex doesn't pull dependencies that aren't on hex.pm. Your error sais: 

```
(module PlugSessionMEMCACHED is not available)
```

So one has to include this in your deps section:

```
 {:mcd, github: "EchoTeam/mcd"}
```

I updated the README section as well. Again, thanks a lot for your contribution!
