### ISSUE TITLE
Connecting to a memcached which runs on other than localhost

### ISSUE THREAD

**Issue by hykw** [gutschilla/plug-session-memcached#3]
It seems that the both IP and port number are hard-coded in lib/plug_session_memcached.ex. Do you have any plan you allow to configure them through a configuration like following?

``` elixir:endpoint.ex
plug Plug.Session,
  store: :memcached,
  host: "memcached.example.jp",
  port: 11211
```

**Comment by gutschilla** [comment]
Hi Hitoshi, Yes it is hard-coded laziness (nobody requeste this feature, though very very simple to implement) until now. 

I will make this configurable through you config.exs/App.env. I tuned fo th featur to appear this week.

Thanks for yo feature request!

**Comment by gutschilla** [comment]
The week is over by now. The memcached connector for the session plugin itself can now be configured in your app's config.exs:

```
config :plug_session_memcached,
  server: [ '127.0.0.1', 11211 ]
```

It's done like this to ensure that the memcached connection is up before the plug starts to access it. I also documented this in both projects [plug-session-memcached](https://github.com/gutschilla/plug-session-memcached) and [phoenix-skeleton](https://github.com/gutschilla/phoenix-skeleton). In the latter the plug configuration stays untouched.

Thanks a million for your input!

**Comment by hykw** [comment]
@gutschilla Thank you, it works perfectly!

**Comment by gutschilla** [comment]
I am happy to hear that - great!
