### ISSUE TITLE
Mac OS X case insensitive file system problem

### ISSUE THREAD

**Issue by kenta-aktsk** [gutschilla/plug-session-memcached#6]
When I download your package (from Github or Hex), I can download only `plug_session_memcached.ex` file.

Your package has `plug_session_memcached.ex` and `plug_session_MEMCACHED.ex`, but file system of Mac OS X is case insensitive.

So I think one of your file is overwritten by another one when downloaded.

Incidentally, when I download your package on Amazon Linux, I can get both `plug_session_memcached.ex` and `plug_session_MEMCACHED.ex`.

I think you should use different file name.

**Comment by gutschilla** [comment]
Hi, thanks for pointing that out. Didn't know that HFS+ is case insensitive. Just like Windows/NTFS is. I will rename that file to work around this.

Again, thanks for you report! Martin

**Comment by gutschilla** [comment]
Fixed with https://github.com/gutschilla/plug-session-memcached/pull/7
